<form action="<?php echo $this->getSubmitUrl(); ?>" method="post">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <table>
        <tr>
            <td>
                <label for="">Nom & Prénom du Client: </label>
            </td>
            <td>
                <input type="text" name="nom"/>
            </td>
        </tr>
        <tr>
            <td>
                <label for="">Date de Livraison: </label>
            </td>
            <td>
                <input type="date" name="date"/>
            </td>
        </tr>
        <tr>
            <td>
                <label for="">Produit Livré: </label>
            </td>
            <td>
                <input type="text" name="produit"/>
            </td>
        </tr>
        <tr>
            <td>
                
            </td>
            <td>
                <input type="submit" value="Envoyer"/>
            </td>
        </tr>
    </table>
</form>